---
# tasks file for ceph-single

- name: Config Ceph Yum Repo.
  template:
    src: "ceph.repo.j2"
    dest: "/etc/yum.repos.d/ceph.repo"
    owner: root
    group: root
    mode: "0644"

- name: Check Exist ceph.conf for Deploy
  stat:
    path: "{{ ceph_single.work_dir }}/ceph.conf"
  register: check_exist_ceph_conf_for_deploy

#- debug: var=check_exist_ceph_conf_for_deploy

- name: Install Ceph Deploy Packages
  yum:
    name: "{{ packages }}"
    state: installed
  vars:
    packages:
      - ceph-deploy
      - epel-release
  when: check_exist_ceph_conf_for_deploy.stat.exists is not defined or check_exist_ceph_conf_for_deploy.stat.exists != True

- name: Create Deploy Work Directory
  file:
    path: "{{ ceph_single.work_dir }}"
    state: directory
    mode: '0755'
  when: check_exist_ceph_conf_for_deploy.stat.exists is not defined or check_exist_ceph_conf_for_deploy.stat.exists != True

- name: Init Deploy New
  shell: |
    ceph-deploy new --public-network {{ ceph_single.network.public }} --cluster-network {{ ceph_single.network.cluster }} {{ ansible_fqdn }}
  args:
    chdir: "{{ ceph_single.work_dir }}"
  when: check_exist_ceph_conf_for_deploy.stat.exists is not defined or check_exist_ceph_conf_for_deploy.stat.exists != True

- name: Add Config to ceph.conf
  blockinfile:
    dest: "{{ ceph_single.work_dir }}/ceph.conf"
    block: |
      osd pool default pg num = 64
      osd pool default pgp num = 64
      mon max pg per osd = 4096
      mon allow pool delete = true
      osd pool default size = 1
      osd mount options xfs = "rw,noatime,attr2,inode64,noquota,discard"
      osd_journal_size = 1024
      osd objectstore = filestore

      [client]
      rbd cache = true
      rbd cache writethrough until flush = true
      rbd concurrent management ops = 20
    backup: yes

- name: Install Ceph Packages
  shell: |
    ceph-deploy install --release {{ ceph_single.release }} {{ ansible_fqdn }}
  args:
    chdir: "{{ ceph_single.work_dir }}"
  when: check_exist_ceph_conf_for_deploy.stat.exists is not defined or check_exist_ceph_conf_for_deploy.stat.exists != True

- name: Disable 'ProtectHome' Systemd Service
  shell: |
    sed -i 's/^ProtectHome=/#ProtectHome=/g' /lib/systemd/system/ceph-mon@.service
  args:
    chdir: "{{ ceph_single.work_dir }}"
  when: check_exist_ceph_conf_for_deploy.stat.exists is not defined or check_exist_ceph_conf_for_deploy.stat.exists != True

- name: Check Exist MON Directory
  stat:
    path: "/var/lib/ceph/mon/ceph-{{ ansible_hostname }}"
  register: check_exist_mon_directory

- name: Create MON
  shell: |
    ceph-deploy mon create-initial
  args:
    chdir: "{{ ceph_single.work_dir }}"
  when: check_exist_mon_directory.stat.exists is undefined or check_exist_mon_directory.stat.exists != True

- name: Check Exist MGR Directory
  stat:
    path: "/var/lib/ceph/mgr/ceph-{{ ansible_fqdn }}"
  register: check_exist_mgr_directory

- name: Create MGR Service
  shell: |
    ceph-deploy mgr create {{ ansible_fqdn }}
  args:
    chdir: "{{ ceph_single.work_dir }}"
  when: check_exist_mgr_directory.stat.exists is undefined or check_exist_mgr_directory.stat.exists != True

- name: Copy Keyring
  copy:
    src: "{{ ceph_single.work_dir }}/{{ item }}"
    dest: "/etc/ceph/{{ item }}"
    owner: root
    group: root
    mode: "0600"
    force: yes
    remote_src: yes
    backup: yes
  with_items:
    - "{{ ceph_single.admin_keyring_name }}"

- name: Create OSD Directory
  file:
    path: "{{ item }}"
    state: directory
    owner: ceph
    group: ceph
    mode: '0755'
  with_items: "{{ ceph_single.osd_path }}"

- name: Prepare OSD
  shell: |
    ceph-disk prepare --filestore {{ item }}
  args:
    chdir: "{{ ceph_single.work_dir }}"
  with_items: "{{ ceph_single.osd_path }}"

- name: Check OSD Service
  shell: |
    systemctl status ceph-osd@{{ item.0 }}
  args:
    chdir: "{{ ceph_single.work_dir }}"
  with_indexed_items: "{{ ceph_single.osd_path }}"
  failed_when: no
  changed_when: false
  register: check_osd_service

#- debug: var=check_osd_service.results

- name: Create OSD
  shell: |
    ceph-deploy osd create {{ ansible_fqdn }} --filestore --data {{ item.1 }} || true
  args:
    chdir: "{{ ceph_single.work_dir }}"
  with_indexed_items: "{{ ceph_single.osd_path }}"
  when: check_osd_service.results[item.0].rc != 0

- name: Activate OSD
  shell: |
    ceph-disk activate {{ item.1 }}
  args:
    chdir: "{{ ceph_single.work_dir }}"
  with_indexed_items: "{{ ceph_single.osd_path }}"
  when: check_osd_service.results[item.0].rc != 0

- name: Create Pool
  shell: |
    ceph osd pool create {{ item.name }} {{ item.pg_num }} replicated
  args:
    chdir: "{{ ceph_single.work_dir }}"
  with_items: "{{ ceph_single.pool }}"

- name: Setup User-Keyring and Permission
  shell: |
    ceph auth get-or-create client.cinder mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool=volumes, allow rwx pool=vms, allow rx pool=images'
    ceph auth get-or-create client.cinder-backup mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool=backups'
    ceph auth get-or-create client.glance mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool=images'
    ceph auth get-or-create client.gnocchi mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool=gnocchi'
  args:
    chdir: "{{ ceph_single.work_dir }}"
  with_items: "{{ ceph_single.pool }}"

