---
- name: Config LimitNOFILE of MariaDB - /etc/systemd/system/mariadb.service.d/limits.conf
  template:
    src: "systemd-limits.conf.j2"
    dest: "/etc/systemd/system/mariadb.service.d/limits.conf"
    owner: root
    group: root
    mode: '0640'
    backup: yes
  notify: Restart MariaDB Galera cluster

- name: Add galera configuration
  template: src=server.cnf.j2 dest=/etc/my.cnf.d/server.cnf
    owner=root group=root mode=0644
  notify: Restart MariaDB Galera cluster

