---
# handlers file for openstack-heat

- name: Restart Heat Service
  systemd:
    name: "{{ item }}"
    state: restarted
  with_items:
    - openstack-heat-api
    - openstack-heat-api-cfn
    - openstack-heat-engine
