---
# tasks file for openstack-neutron-network

- name: Install Neutron Package
  yum:
    name: "{{ packages }}"
    state: installed
  vars:
    packages:
      - openstack-neutron
      - openstack-neutron-ml2
      - openstack-neutron-openvswitch
      - openstack-neutron-metering-agent
      #- openstack-neutron-linuxbridge

#########################################################

- name: Config Neutron - /etc/neutron/neutron.conf
  template:
    src: "neutron.conf.j2"
    dest: "/etc/neutron/neutron.conf"
    owner: root
    group: neutron
    mode: '0640'
    backup: yes
  notify: Restart Neutron Service - Network::ALL

- name: Config Neutron - /etc/neutron/plugins/ml2/ml2_conf.ini
  template:
    src: "ml2_conf.ini.j2"
    dest: "/etc/neutron/plugins/ml2/ml2_conf.ini"
    owner: root
    group: neutron
    mode: '0640'
    backup: yes
  notify: Restart Neutron Service - Network::ALL

- name: Config Neutron - /etc/neutron/dnsmasq-neutron.conf
  template:
    src: "dnsmasq-neutron.conf.j2"
    dest: "/etc/neutron/dnsmasq-neutron.conf"
    owner: root
    group: neutron
    mode: '0644'
    backup: yes
  notify: Restart Neutron Service - neutron-dhcp-agent

- name: Config Neutron - /etc/neutron/dhcp_agent.ini
  template:
    src: "dhcp_agent.ini.j2"
    dest: "/etc/neutron/dhcp_agent.ini"
    owner: root
    group: neutron
    mode: '0640'
    backup: yes
  notify: Restart Neutron Service - neutron-dhcp-agent

- name: Config Neutron - /etc/neutron/l3_agent.ini
  template:
    src: "l3_agent.ini.j2"
    dest: "/etc/neutron/l3_agent.ini"
    owner: root
    group: neutron
    mode: '0640'
    backup: yes
  notify: Restart Neutron Service - neutron-l3-agent

- name: Config Neutron - /etc/neutron/metadata_agent.ini
  template:
    src: "metadata_agent.ini.j2"
    dest: "/etc/neutron/metadata_agent.ini"
    owner: root
    group: neutron
    mode: '0640'
    backup: yes
  notify: Restart Neutron Service - neutron-metadata-agent

- name: Config Neutron - /etc/neutron/metering_agent.ini
  template:
    src: "metering_agent.ini.j2"
    dest: "/etc/neutron/metering_agent.ini"
    owner: root
    group: neutron
    mode: '0640'
    backup: yes
  notify: Restart Neutron Service - neutron-metering-agent

- name: Config Neutron - /etc/neutron/plugins/ml2/openvswitch_agent.ini
  template:
    src: "openvswitch_agent.ini.j2"
    dest: "/etc/neutron/plugins/ml2/openvswitch_agent.ini"
    owner: root
    group: neutron
    mode: '0640'
    backup: yes
  notify: Restart Neutron Service - neutron-openvswitch-agent

- name: Ensure Neutron Service Running - ALL
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - neutron-dhcp-agent
    - neutron-l3-agent
    - neutron-metadata-agent
    - neutron-metering-agent
    - neutron-openvswitch-agent

