---
# tasks file for openstack-horizon

- name: Install Horizon Package
  yum:
    name: "{{ packages }}"
    state: installed
  vars:
    packages:
      - openstack-dashboard
      - openstack-heat-ui
      - openstack-octavia-ui

#########################################################

- name: Config HTTPd for Horizon - /etc/openstack-dashboard/local_settings
  template:
    src: "local_settings.j2"
    dest: "/etc/openstack-dashboard/local_settings"
    owner: root
    group: apache
    mode: '0640'
    backup: yes
  notify: Restart HTTPd Service

- name: Config HTTPd for Horizon - /etc/httpd/conf.d/openstack-dashboard.conf
  template:
    src: "openstack-dashboard.conf.j2"
    dest: "/etc/httpd/conf.d/openstack-dashboard.conf"
    owner: root
    group: root
    mode: '0644'
    backup: yes
  notify: Restart HTTPd Service

