---
# handlers file for openstack-gnocchi

- name: Restart Gnocchi Service
  systemd:
    name: "{{ item }}"
    state: restarted
  with_items:
    - openstack-gnocchi-api
    - openstack-gnocchi-metricd
